name: Cut New Tag from Main

on:
  repository_dispatch:
    types:
      - tag-release

jobs:
  tag-release:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Tag Release
        uses: mathieudutour/github-tag-action@v5.4
        with:
          github_token: ${{ secrets.TAGGING_AUTH_TOKEN }}
          release_branches: main,master
